// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// GCElin_gradFunct
SEXP GCElin_gradFunct();
RcppExport SEXP _GCEmodels_GCElin_gradFunct() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    rcpp_result_gen = Rcpp::wrap(GCElin_gradFunct());
    return rcpp_result_gen;
END_RCPP
}
// GCElin_objFunct
SEXP GCElin_objFunct();
RcppExport SEXP _GCEmodels_GCElin_objFunct() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    rcpp_result_gen = Rcpp::wrap(GCElin_objFunct());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GCEmodels_GCElin_gradFunct", (DL_FUNC) &_GCEmodels_GCElin_gradFunct, 0},
    {"_GCEmodels_GCElin_objFunct", (DL_FUNC) &_GCEmodels_GCElin_objFunct, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_GCEmodels(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
