# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
GCElin_gradFunct <- function() {
    .Call(`_ProvaProjEigen_GCElin_gradFunct`)
}

#' @export
GCElin_objFunct <- function() {
    .Call(`_ProvaProjEigen_GCElin_objFunct`)
}

rcppeigen_hello_world <- function() {
    .Call(`_ProvaProjEigen_rcppeigen_hello_world`)
}

rcppeigen_outerproduct <- function(x) {
    .Call(`_ProvaProjEigen_rcppeigen_outerproduct`, x)
}

rcppeigen_innerproduct <- function(x) {
    .Call(`_ProvaProjEigen_rcppeigen_innerproduct`, x)
}

rcppeigen_bothproducts <- function(x) {
    .Call(`_ProvaProjEigen_rcppeigen_bothproducts`, x)
}

