# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
GCElin_gradFunct <- function() {
    .Call(`_GCEmodels_GCElin_gradFunct`)
}

#' @export
GCElin_objFunct <- function() {
    .Call(`_GCEmodels_GCElin_objFunct`)
}

